FROM redmine:latest

RUN git clone https://github.com/taikii/redmine_mermaid_macro.git /usr/src/redmine/plugins/redmine_mermaid_macro \
&&  git clone https://github.com/maxrossello/redmine_pluggable_themes.git /usr/src/redmine/plugins/redmine_pluggable_themes \
&&  git clone https://github.com/maxrossello/redmine_themes.git /usr/src/redmine/plugins/redmine_themes \
&&  git clone https://github.com/mrliptontea/PurpleMine2.git /usr/src/redmine/public/themes/PurpleMine2

