version: '3.1'

services:
  redmine:
    image: redmine:afmconfig
    restart: always
    depends_on:
      - redmine_db
    container_name: redmine_web
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: 
      REDMINE_SECRET_KEY_BASE: 

  redmine_db:
    image: mysql:5.7
    restart: always
    container_name: redmine_db
    volumes:
    - type: bind
      source: /home/maule2/tmp
      target: /home/redmine/tmp
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: 
