version: '3.1'

services:
  redmine:
    image: bliptrip/redmine:afmconfig
    restart: always
    depends_on:
      - redmine_db
    container_name: redmine_web
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: password
      REDMINE_SECRET_KEY_BASE: secret

  redmine_db:
    image: mysql:5.7
    restart: always
    container_name: redmine_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
